version: "3.3"
services:
  bot:
    restart: always
    image: ericrigsb/bitl_craig
    working_dir: /bitl_craig
    volumes: 
      - ./data/rec:/bitl_craig/rec
      - ./overrides/config.json:/bitl_craig/config.json:ro
      - ./overrides/index.php:/bitl_craig/web/index.php:ro
    networks:
      - host
    ports:
      - "80:80"
    command: bash -c "chmod a+x ./init.sh; ./init.sh"
networks:
  host:
